# Generated by Django 4.1 on 2023-02-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
